# Header
menu:
  主页: /
  所有文章: /archives
  Java拾遗: /tags/java
  Linux: /tags/linux
  性能实验室: /tags/performance
  相册: /instagram
  
# SubNav
subnav:
  github: "https://github.com/XHao"
  linkedin: "https://cn.linkedin.com/pub/%E6%98%8A-%E8%B0%A2/30/70a/245"
  rss: "/atom.xml"
  #zhihu: "http://www.zhihu.com/people/hao-xie-88"
  #douban: "#"
  mail: "mailto:sei_xh2006@126.com"
  #google: "#"
  #twitter: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-113278033-1'
favicon: /img/favicon.ico

#你的头像url
avatar: /img/neko.jpg
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 生活在魔都的一枚攻城狮
